### ISSUE TITLE
Configure environment to visualize the design

### ISSUE THREAD

**Issue by KaoruNishikawa** [necst-telescope/design#1]
- [ ] ~#3~ Will be tracked in #8.
- [x] #4

from (multiple) TOML file(s) of format:

```toml
[necst.subpackage.module_name1]
ClassName = { type = "class", publish = ["/topic1"], subscription = ["/namespace/topic2"], description = "" }
function_name = { type = "function" }
[necst.subpackage.module_name2]
```
